ln -s /media/Films1/AClasser/ AClasser
ln -s //media/Jeux/Shares/Annales Annales
ln -s /media/BluRays/Shares/Bluray Bluray
ln -s /media/Films1/Shares/Films/ Films1
ln -s /media/Jeux/Shares/Jeux/ Jeux
ln -s /media/Jeux/Shares/Logiciels/ Logiciels
ln -s /media/Jeux/Shares/Manga/ Mangas
ln -s /media/Films2/Shares/Films2/Porno/ NSFW
ln -s /usr/share/phpmyadmin/ phpmyadmin
ln -s /media/Series1/Shares/Séries/ Series
